# Generated by Django 4.1.4 on 2022-12-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitchbooking', '0002_bookingsettings_rename_end_time_booking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_mobile',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_name',
        ),
    ]
