# Generated by Django 4.1.4 on 2022-12-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitchbooking', '0004_alter_bookingsettings_period_of_each_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pitch',
        ),
    ]
