# Generated by Django 2.2.4 on 2020-03-24 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profiles')),
                ('birth_date', models.DateField(null=True)),
                ('foot_choice', models.CharField(choices=[('r', 'Right'), ('l', 'Left'), ('b', 'Both')], max_length=1, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('pns', 'Prefer not to say')], max_length=1, null=True)),
                ('current_status', models.CharField(blank=True, help_text='free agent or playing for larriskos  fc', max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_profile', 'view profile'), ('add_profile', 'Add profile'), ('delete_profile', 'Delete profile')),
            },
        ),
    ]
