# Generated by Django 3.2.16 on 2022-10-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('pns', 'Prefer not to say')], max_length=3, null=True),
        ),
    ]
