---
linters:
    pep8:
        python: 3
        ignore: 'W28'
        max-line-length: 80
        fixer: true

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'


branches:
    # Ignore pull requests to the named branches
    ignore:
        - 'wip'
        - 'feedback'

review:
    # Don't use 'failure' build status when
    # a pull request contains style errors.
    fail_on_comments: false