language: python
notifications:
  email:
    recipients:
      - iamfeysal@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

script:

 - python manage.py makemigrations
 - python manage.py migrate
 - python manage.py test

after_success:
- bash < (curl -s https://codecov.io/bash)

“scripts”: {
 — nosetests auth/test.py -v — with-coverage
}