# Generated by Django 2.2.4 on 2019-12-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
